//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLocalVet.Languages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheLocalVet.Languages.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big vet.
        /// </summary>
        public static string bigvet {
            get {
                return ResourceManager.GetString("bigvet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string NearestVetSinglePageAddress {
            get {
                return ResourceManager.GetString("NearestVetSinglePageAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competency.
        /// </summary>
        public static string NearestVetSinglePageCompetency {
            get {
                return ResourceManager.GetString("NearestVetSinglePageCompetency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise.
        /// </summary>
        public static string NearestVetSinglePageExpertise {
            get {
                return ResourceManager.GetString("NearestVetSinglePageExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Visit.
        /// </summary>
        public static string NearestVetSinglePageHomeVisit {
            get {
                return ResourceManager.GetString("NearestVetSinglePageHomeVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NearestVetSinglePageName {
            get {
                return ResourceManager.GetString("NearestVetSinglePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hours.
        /// </summary>
        public static string NearestVetSinglePageOpeningHours {
            get {
                return ResourceManager.GetString("NearestVetSinglePageOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string NearestVetSinglePageTitle {
            get {
                return ResourceManager.GetString("NearestVetSinglePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured in ParseHelper.
        /// </summary>
        public static string ParseHelperError {
            get {
                return ResourceManager.GetString("ParseHelperError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small vet.
        /// </summary>
        public static string smallvet {
            get {
                return ResourceManager.GetString("smallvet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in map.
        /// </summary>
        public static string ViewInMap {
            get {
                return ResourceManager.GetString("ViewInMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
