// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TheLocalVet.Languages {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TheLocalVet.Languages.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string bigvet {
            get {
                return ResourceManager.GetString("bigvet", resourceCulture);
            }
        }
        
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string NearestVetSinglePageAddress {
            get {
                return ResourceManager.GetString("NearestVetSinglePageAddress", resourceCulture);
            }
        }
        
        public static string NearestVetSinglePageCompetency {
            get {
                return ResourceManager.GetString("NearestVetSinglePageCompetency", resourceCulture);
            }
        }
        
        public static string NearestVetSinglePageExpertise {
            get {
                return ResourceManager.GetString("NearestVetSinglePageExpertise", resourceCulture);
            }
        }
        
        public static string NearestVetSinglePageHomeVisit {
            get {
                return ResourceManager.GetString("NearestVetSinglePageHomeVisit", resourceCulture);
            }
        }
        
        public static string NearestVetSinglePageName {
            get {
                return ResourceManager.GetString("NearestVetSinglePageName", resourceCulture);
            }
        }
        
        public static string NearestVetSinglePageOpeningHours {
            get {
                return ResourceManager.GetString("NearestVetSinglePageOpeningHours", resourceCulture);
            }
        }
        
        public static string NearestVetSinglePageTitle {
            get {
                return ResourceManager.GetString("NearestVetSinglePageTitle", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string ParseHelperError {
            get {
                return ResourceManager.GetString("ParseHelperError", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string smallvet {
            get {
                return ResourceManager.GetString("smallvet", resourceCulture);
            }
        }
        
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string ViewInMap {
            get {
                return ResourceManager.GetString("ViewInMap", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string FailedToFindVet {
            get {
                return ResourceManager.GetString("FailedToFindVet", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string SearchNearestVetLabel {
            get {
                return ResourceManager.GetString("SearchNearestVetLabel", resourceCulture);
            }
        }
        
        public static string SearchNearestVetLocation {
            get {
                return ResourceManager.GetString("SearchNearestVetLocation", resourceCulture);
            }
        }
        
        public static string SearchNearestVetLocationLabel {
            get {
                return ResourceManager.GetString("SearchNearestVetLocationLabel", resourceCulture);
            }
        }
        
        public static string SearchNearestVetPickerText {
            get {
                return ResourceManager.GetString("SearchNearestVetPickerText", resourceCulture);
            }
        }
        
        public static string SearchNearestVetPlace {
            get {
                return ResourceManager.GetString("SearchNearestVetPlace", resourceCulture);
            }
        }
        
        public static string SearchNearestVetPlaceLabel {
            get {
                return ResourceManager.GetString("SearchNearestVetPlaceLabel", resourceCulture);
            }
        }
        
        public static string SearchPlaceIsEmpty {
            get {
                return ResourceManager.GetString("SearchPlaceIsEmpty", resourceCulture);
            }
        }
        
        public static string SearchNearestVetDistance {
            get {
                return ResourceManager.GetString("SearchNearestVetDistance", resourceCulture);
            }
        }
        
        public static string FeedbackEmailSubject {
            get {
                return ResourceManager.GetString("FeedbackEmailSubject", resourceCulture);
            }
        }
        
        public static string FeedbackText {
            get {
                return ResourceManager.GetString("FeedbackText", resourceCulture);
            }
        }
        
        public static string FeedbackTitleText {
            get {
                return ResourceManager.GetString("FeedbackTitleText", resourceCulture);
            }
        }
        
        public static string InfoPageTitle {
            get {
                return ResourceManager.GetString("InfoPageTitle", resourceCulture);
            }
        }
        
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        public static string InfoTitleText {
            get {
                return ResourceManager.GetString("InfoTitleText", resourceCulture);
            }
        }
        
        public static string NearestVetPageTitle {
            get {
                return ResourceManager.GetString("NearestVetPageTitle", resourceCulture);
            }
        }
        
        public static string SendFeedbackButtonText {
            get {
                return ResourceManager.GetString("SendFeedbackButtonText", resourceCulture);
            }
        }
        
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        public static string OpenWeb {
            get {
                return ResourceManager.GetString("OpenWeb", resourceCulture);
            }
        }
        
        public static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
            }
        }
        
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
    }
}
