//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLocalVet.Languages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheLocalVet.Languages.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big vet.
        /// </summary>
        public static string bigvet {
            get {
                return ResourceManager.GetString("bigvet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately we could not locate any vets in the area you searched. Try again, and maybe widen the search area..
        /// </summary>
        public static string FailedToFindVet {
            get {
                return ResourceManager.GetString("FailedToFindVet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Local Vet feedback.
        /// </summary>
        public static string FeedbackEmailSubject {
            get {
                return ResourceManager.GetString("FeedbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fhjoids fsd hfoisduf jhwenf irehg9e8o g0rs gr gjpifd jvfid jofidghiofdn gviofd iofd goifd hiogdf .
        /// </summary>
        public static string FeedbackText {
            get {
                return ResourceManager.GetString("FeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackTitleText {
            get {
                return ResourceManager.GetString("FeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoPageTitle {
            get {
                return ResourceManager.GetString("InfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hgiordjgnoifdhgoishfiusdhfiusdgfu9dsgh us ifu sdhuf sdhofsdho fse fhosd fhosdi fodis fidos fos jfiods ohids fsd.
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoTitleText {
            get {
                return ResourceManager.GetString("InfoTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Vet.
        /// </summary>
        public static string NearestVetPageTitle {
            get {
                return ResourceManager.GetString("NearestVetPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string NearestVetSinglePageAddress {
            get {
                return ResourceManager.GetString("NearestVetSinglePageAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competency.
        /// </summary>
        public static string NearestVetSinglePageCompetency {
            get {
                return ResourceManager.GetString("NearestVetSinglePageCompetency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise.
        /// </summary>
        public static string NearestVetSinglePageExpertise {
            get {
                return ResourceManager.GetString("NearestVetSinglePageExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Visit.
        /// </summary>
        public static string NearestVetSinglePageHomeVisit {
            get {
                return ResourceManager.GetString("NearestVetSinglePageHomeVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NearestVetSinglePageName {
            get {
                return ResourceManager.GetString("NearestVetSinglePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hours.
        /// </summary>
        public static string NearestVetSinglePageOpeningHours {
            get {
                return ResourceManager.GetString("NearestVetSinglePageOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string NearestVetSinglePageTitle {
            get {
                return ResourceManager.GetString("NearestVetSinglePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured in ParseHelper.
        /// </summary>
        public static string ParseHelperError {
            get {
                return ResourceManager.GetString("ParseHelperError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string SearchNearestVetDistance {
            get {
                return ResourceManager.GetString("SearchNearestVetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by place or your location.
        /// </summary>
        public static string SearchNearestVetLabel {
            get {
                return ResourceManager.GetString("SearchNearestVetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By your location.
        /// </summary>
        public static string SearchNearestVetLocation {
            get {
                return ResourceManager.GetString("SearchNearestVetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search near your location.
        /// </summary>
        public static string SearchNearestVetLocationLabel {
            get {
                return ResourceManager.GetString("SearchNearestVetLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search type.
        /// </summary>
        public static string SearchNearestVetPickerText {
            get {
                return ResourceManager.GetString("SearchNearestVetPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By place.
        /// </summary>
        public static string SearchNearestVetPlace {
            get {
                return ResourceManager.GetString("SearchNearestVetPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by place.
        /// </summary>
        public static string SearchNearestVetPlaceLabel {
            get {
                return ResourceManager.GetString("SearchNearestVetPlaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using search by place the text field cannot be empty..
        /// </summary>
        public static string SearchPlaceIsEmpty {
            get {
                return ResourceManager.GetString("SearchPlaceIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string SendFeedbackButtonText {
            get {
                return ResourceManager.GetString("SendFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small vet.
        /// </summary>
        public static string smallvet {
            get {
                return ResourceManager.GetString("smallvet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in map.
        /// </summary>
        public static string ViewInMap {
            get {
                return ResourceManager.GetString("ViewInMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
